#!/usr/bin/env ruby
#
# The environment variable FAILCOUNT should have the filename of a state file
# that has the number of times fixture should crash with exit code 127 before
# succeeding.

failcount_file = ENV['FAILCOUNT']

action = 'succeed'
delay = ARGV[0].to_i

if File.exist?(failcount_file)
  failcount = File.read(failcount_file).to_i
  if failcount == 0
    action = 'succeed'
  else
    File.open(failcount_file, 'w') { |f| f.puts(failcount - 1) }
    action = 'fail'
  end
end

sleep delay

case action
  when 'succeed'
    exit 0
  when 'fail'
    exit 127
  when 'hang'
    sleep(1000)
  else
    puts('WTF MAN')
    exit 2
end
