#!/usr/bin/env ruby

HANG_CHECK_INTERVAL = 5
HANG_COUNT = 5
MAX_RETRIES = 5

commandline = ARGV.join(' ')

def process_looks_hung(pid)
  false
end

retries_left = MAX_RETRIES

while retries_left > 0
  retries_left -= 1
  childpid = Process.fork
  child_exitstatus = nil

  if childpid # WE IS PARENT
    Signal.trap("CHLD") do
      puts("Child died (or stopped but let's ignore that)")
      Process.wait(childpid)
      unless $?.exited?
        puts("Child wait completed but it has not exited, WTF?")
        exit 2
      end
      if $?.exitstatus == 0
        puts("Child completed successfully")
        exit 0
      end
      puts("Child exited with status #{$?.exitstatus}")
      child_exitstatus = $?.exitstatus
    end
    until child_exitstatus do
      sleep HANG_CHECK_INTERVAL
      if process_looks_hung(childpid)
        Process.kill(childpid)
      else
        puts("Child still appears to be doing something worthwhile")
      end
    end
  else # WE IS CHILD
    exec(commandline)
  end
end
